import QRCode from 'qrcode';
import jsPDF from 'jspdf';

export type QrPayload = {
  componentId: string; railwayZone: string; trackNumber: string;
  installationDate: string; manufacturingDetails: string; qrId: string;
};

export function buildQrPayload(p: QrPayload): string {
  return `RAILQR:v1|CID:${p.componentId}|QRID:${p.qrId}|ZONE:${p.railwayZone}|TRACK:${p.trackNumber}|INST:${p.installationDate}|MFG:${p.manufacturingDetails}`;
}

export async function generateQrDataUrl(text: string): Promise<string> {
  return QRCode.toDataURL(text, { width: 320, margin: 2, color: { dark: '#0b1f3a', light: '#ffffff' }, errorCorrectionLevel: 'M' });
}

export async function downloadQrPng(text: string, filename: string) {
  const dataUrl = await generateQrDataUrl(text);
  const link = document.createElement('a');
  link.href = dataUrl; link.download = `${filename}.png`; link.click();
}

export function downloadQrPdf(payload: QrPayload, qrDataUrl: string, filename: string) {
  const doc = new jsPDF({ unit: 'mm', format: 'a4' });
  const pageW = doc.internal.pageSize.getWidth();
  doc.setFillColor(11, 31, 58); doc.rect(0, 0, pageW, 30, 'F');
  doc.setTextColor(255, 255, 255); doc.setFontSize(18); doc.setFont('helvetica', 'bold');
  doc.text('RailQR AI — QR Code Marking Sheet', 14, 18);
  doc.setFontSize(10); doc.setFont('helvetica', 'normal');
  doc.text('Indian Railways — Laser-Based QR Marking System', 14, 25);
  doc.addImage(qrDataUrl, 'PNG', pageW - 60, 40, 46, 46);
  doc.setTextColor(20, 20, 20); doc.setFontSize(13); doc.setFont('helvetica', 'bold');
  doc.text('Component Details', 14, 45);
  doc.setFontSize(11); doc.setFont('helvetica', 'normal');
  let y = 55;
  const rows: [string, string][] = [
    ['Component ID', payload.componentId], ['QR ID', payload.qrId],
    ['Railway Zone', payload.railwayZone], ['Track Number', payload.trackNumber],
    ['Installation Date', payload.installationDate], ['Manufacturing Details', payload.manufacturingDetails],
  ];
  for (const [label, value] of rows) {
    doc.setFont('helvetica', 'bold'); doc.text(`${label}:`, 14, y);
    doc.setFont('helvetica', 'normal'); doc.text(value, 60, y); y += 8;
  }
  doc.setDrawColor(200, 200, 200); doc.line(14, y + 2, pageW - 14, y + 2);
  doc.setFontSize(8); doc.setTextColor(120, 120, 120);
  doc.text(`Generated by RailQR AI on ${new Date().toLocaleString()}`, 14, y + 8);
  doc.save(`${filename}.pdf`);
}

export function exportCsv(filename: string, headers: string[], rows: (string | number | null)[][]) {
  const escape = (v: string | number | null) => {
    if (v === null || v === undefined) return '';
    const s = String(v);
    return s.includes(',') || s.includes('"') || s.includes('\n') ? `"${s.replace(/"/g, '""')}"` : s;
  };
  const csv = [headers.join(','), ...rows.map((r) => r.map(escape).join(','))].join('\n');
  const blob = new Blob([csv], { type: 'text/csv;charset=utf-8;' });
  const link = document.createElement('a');
  link.href = URL.createObjectURL(blob); link.download = `${filename}.csv`; link.click();
  URL.revokeObjectURL(link.href);
}

export function exportExcel(filename: string, headers: string[], rows: (string | number | null)[][]) {
  const escapeXml = (v: string | number | null) => String(v ?? '').replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;');
  const headerRow = headers.map((h) => `<Cell><Data ss:Type="String">${escapeXml(h)}</Data></Cell>`).join('');
  const dataRows = rows.map((r) => `<Row>${r.map((v) => `<Cell><Data ss:Type="${typeof v === 'number' ? 'Number' : 'String'}">${escapeXml(v)}</Data></Cell>`).join('')}</Row>`).join('\n');
  const xml = `<?xml version="1.0"?>\n<?mso-application progid="Excel.Sheet"?>\n<Workbook xmlns="urn:schemas-microsoft-com:office:spreadsheet" xmlns:ss="urn:schemas-microsoft-com:office:spreadsheet">\n<Worksheet ss:Name="Sheet1"><Table>\n<Row>${headerRow}</Row>\n${dataRows}\n</Table></Worksheet></Workbook>`;
  const blob = new Blob([xml], { type: 'application/vnd.ms-excel;charset=utf-8;' });
  const link = document.createElement('a');
  link.href = URL.createObjectURL(blob); link.download = `${filename}.xls`; link.click();
  URL.revokeObjectURL(link.href);
}

export async function generateQrSvg(text: string): Promise<string> {
  const svg = await QRCode.toString(text, { type: 'svg', margin: 2, color: { dark: '#0b1f3a', light: '#ffffff' }, errorCorrectionLevel: 'M' });
  return svg.replace(/<svg /, '<svg width="240" height="240" ');
}

export function downloadSvg(svgStr: string, filename: string) {
  const blob = new Blob([svgStr], { type: 'image/svg+xml;charset=utf-8;' });
  const link = document.createElement('a');
  link.href = URL.createObjectURL(blob); link.download = `${filename}.svg`; link.click();
  URL.revokeObjectURL(link.href);
}

export function printQr(htmlContent: string) {
  const w = window.open('', '_blank');
  if (!w) return;
  w.document.write(htmlContent);
  w.document.close();
  w.focus();
  setTimeout(() => { w.print(); w.close(); }, 300);
}

export function generateQrId(componentId: string): string {
  const zone = componentId.slice(0, 3).toUpperCase().replace(/[^A-Z0-9]/g, '');
  const rand = Math.random().toString(36).slice(2, 8).toUpperCase();
  const ts = Date.now().toString(36).slice(-5).toUpperCase();
  return `RQR-${zone || 'XXX'}-${ts}${rand}`;
}
